### ISSUE TITLE
Does formatting uncertain protein change ignore format options?

### ISSUE THREAD

**Issue by k-kom** [chrovis/clj-hgvs#7]
I've encountered an HGVS string like `"p.(Met918Thr)"` and the specification says it represents [predicated protein change](https://varnomen.hgvs.org/recommendations/uncertain/).

> in p.(Cys123Gly) indicating the amino acid change is predicted from DNA level data (no experimental proof) 

It looks like this `"()"` disrupts formatting like below.

```clojure
dev> (hgvs/format (hgvs/parse "p.(Met918Thr)")
                  {:amino-acid-format :short})
"p.(Met918Thr)"
dev> (hgvs/format (hgvs/parse "p.Met918Thr")
                  {:amino-acid-format :short})
"p.M918T"
```

Is it intended?

**Comment by totakke** [comment]
Not intended. That is a bug. I will fix it soon. Thank you for reporting. 🙇
